import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeContextProvider } from "@/hooks/useContext";
import { ImageKitProvider } from "@imagekit/next";
import { Suspense } from "react";
import Loading from "@/app/loading";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ImageKitProvider
      urlEndpoint={process.env.NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
    >
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <body
            suppressHydrationWarning
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
          >
            <ThemeContextProvider>
              {/* header */}
              <Header />
              {/* main */}

              <main className="min-h-screen">
                <Suspense fallback={<Loading />}>{children} </Suspense>
              </main>

              {/* footer */}
              <Footer />
            </ThemeContextProvider>
          </body>
        </html>
      </ClerkProvider>
    </ImageKitProvider>
  );
}
