import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
// import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "daily thoughts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="none">
      <body className=" h-screen bg-screen ">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
